/*
 * Anakha's Book Store
 * Hey there!<br>   Looking for some interesting books to read?<br>   Then this is the right place for u.   Have a good read!   
 *
 * OpenAPI spec version: 1.0.11
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.40
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Book model module.
 * @module model/Book
 * @version 1.0.11
 */
export class Book {
  /**
   * Constructs a new <code>Book</code>.
   * @alias module:model/Book
   * @class
   * @param ID {Number} 
   * @param title {String} 
   */
  constructor(ID, title) {
    this.ID = ID;
    this.title = title;
  }

  /**
   * Constructs a <code>Book</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Book} obj Optional instance to populate.
   * @return {module:model/Book} The populated <code>Book</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Book();
      if (data.hasOwnProperty('ID'))
        obj.ID = ApiClient.convertToType(data['ID'], 'Number');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('author'))
        obj.author = ApiClient.convertToType(data['author'], 'String');
      if (data.hasOwnProperty('publisher'))
        obj.publisher = ApiClient.convertToType(data['publisher'], 'String');
      if (data.hasOwnProperty('ISBN'))
        obj.ISBN = ApiClient.convertToType(data['ISBN'], 'String');
      if (data.hasOwnProperty('pubdate'))
        obj.pubdate = ApiClient.convertToType(data['pubdate'], 'String');
      if (data.hasOwnProperty('nopg'))
        obj.nopg = ApiClient.convertToType(data['nopg'], 'Number');
      if (data.hasOwnProperty('genre'))
        obj.genre = ApiClient.convertToType(data['genre'], 'String');
    }
    return obj;
  }
}

/**
 * @member {Number} ID
 */
Book.prototype.ID = undefined;

/**
 * @member {String} title
 */
Book.prototype.title = undefined;

/**
 * @member {String} author
 */
Book.prototype.author = undefined;

/**
 * @member {String} publisher
 */
Book.prototype.publisher = undefined;

/**
 * @member {String} ISBN
 */
Book.prototype.ISBN = undefined;

/**
 * @member {String} pubdate
 */
Book.prototype.pubdate = undefined;

/**
 * @member {Number} nopg
 */
Book.prototype.nopg = undefined;

/**
 * @member {String} genre
 */
Book.prototype.genre = undefined;

